[phases.setup]
nixPkgs = [
  "python313",
  "libGL",
  "glib",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libxcb",
  "xorg.libXau",
  "xorg.libXdmcp",
  "libxkbcommon"
]

[start]
cmd = "gunicorn main:app"